### PR TITLE
Changed Firebase Endpoint for linter, exchange, and wrapper

### PR DESCRIPTION
**Pull request by stellawang196**
Change endpoints to FinRL firebase endpoint for linter, exchange, and ad wrapper. #6

### CODE REVIEW

**Review by andrlime — COMMENTED** [review]
looks ok to me

**Review by echavemann — APPROVED** [review]
as long as this is tested shud be good

**Comment by andrlime** [comment]
Please change these to the newest endpoints, see the newest config on the newest Firebase projec

**Review by andrlime — CHANGES_REQUESTED** [review]
Find the newest endpoints. These are the correct places to change, but I had to make a new project on Firebase, so the URLs probably aren't correct anymore.

**Pull request closed without merging**
